/*!CK:793631836!*//*1383457457,173205835*/

if (self.CavalryLogger) { CavalryLogger.start_js(["9jqbv"]); }

__d("GroupsMemberCountUpdater",["Arbiter","DOM"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('DOM');function i(){}i.subscribeMemberCount=function(j){g.subscribe('GroupsMemberCount/changeText',function(k,l){h.setContent(j,l);});};i.subscribeNewMemberCount=function(j){g.subscribe('GroupsMemberCount/changeNewMembersText',function(k,l){h.setContent(j,l);});};e.exports=i;});
__d("GroupsRefreshHandler",["UIPagelet","ge","$"],function(a,b,c,d,e,f){var g=b('UIPagelet'),h=b('ge'),i=b('$'),j=[];function k(l,m){"use strict";this.$GroupsRefreshHandler0=l;this.$GroupsRefreshHandler1=m;j[l]=this;}k.refresh=function(l,m){"use strict";var n=j[m],o=h(m);if(!n||!o)return;n.reloadAds(o,l);};k.prototype.reloadAds=function(l,m){"use strict";this.$GroupsRefreshHandler2=m;g.loadFromEndpoint('WebEgoPane',l,{dom_id:this.$GroupsRefreshHandler0,pid:this.$GroupsRefreshHandler1.pid,data:this.$GroupsRefreshHandler1.data},{bundle:false,displayCallback:this.$GroupsRefreshHandler3.bind(this)});};k.prototype.$GroupsRefreshHandler3=function(l){"use strict";l();i(this.$GroupsRefreshHandler0).appendChild(this.$GroupsRefreshHandler2);};e.exports=k;});
__d("GroupSearchBox",["CSS","DOM","Event","Input","copyProperties"],function(a,b,c,d,e,f){var g=b('CSS'),h=b('DOM'),i=b('Event'),j=b('Input'),k=b('copyProperties'),l={init:function(m,n){var o=h.find(n,'.inputtext');i.listen(m,'click',function(){g.show(n);o.focus();});i.listen(o,'blur',function(){if(!j.getValue(o))g.hide(n);});}};e.exports=l;});
__d("GroupsAddTypeaheadView",["Arbiter","ContextualTypeaheadView"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('ContextualTypeaheadView');for(var i in h)if(h.hasOwnProperty(i))k[i]=h[i];var j=h===null?null:h.prototype;k.prototype=Object.create(j);k.prototype.constructor=k;k.__superConstructor__=h;function k(){"use strict";if(h!==null)h.apply(this,arguments);}k.prototype.select=function(l){"use strict";var m=this.results[this.index];g.inform('GroupsMemberSuggestion/remove',m.uid);if(m.is_member){this.reset();}else j.select.call(this,l);};e.exports=k;});
__d("GroupsAddMemberTypeahead",["Arbiter","DOM","Typeahead","copyProperties","ge"],function(a,b,c,d,e,f){var g=b('Arbiter'),h=b('DOM'),i=b('Typeahead'),j=b('copyProperties'),k=b('ge');function l(m,n){if(m&&n)this.init(m,n);}j(l.prototype,{init:function(m,n){m.subscribe('select',function(o,p){g.inform('GroupsAddMemberTypeahead/add',{gid:n,uid:p.selected.uid,name:p.selected.text,photo:p.selected.photo});var q=m.getData().getExclusions();q.push(p.selected.uid);m.getData().setExclusions(q);});g.subscribe('GroupsAddMemberTypeahead/updateGroupToken',this.resetTypeaheadCaches.bind(this));},resetTypeaheadCaches:function(m,n){var o=h.scry(k('pagelet_group_'),'.uiTypeahead:not(.uiPlacesTypeahead)');for(var p=0;p<o.length;p++){var q=i.getInstance(o[p]);if(q){var r=q.getData();r.updateToken(n.token);q.getCore().subscribe('focus',r.bootstrap.bind(r));}}}});e.exports=l;});
__d("legacy:GroupsAddMemberTypeahead",["GroupsAddMemberTypeahead"],function(a,b,c,d){a.GroupsAddMemberTypeahead=b('GroupsAddMemberTypeahead');},3);
__d("LitestandRHCAds",["AdsRefreshHandler","Arbiter","DOM","Event","LitestandMessages","Run","SubscriptionsHandler","csx","ge"],function(a,b,c,d,e,f){var g=b('AdsRefreshHandler'),h=b('Arbiter'),i=b('DOM'),j=b('Event'),k=b('LitestandMessages'),l=b('Run'),m=b('SubscriptionsHandler'),n=b('csx'),o=b('ge'),p,q,r,s,t;function u(){q&&q.forceLoadIfEnoughTimePassed(0);}function v(){var aa=i.scry(r,"._5f85 a")[0];if(aa)p.addSubscriptions(j.listen(aa,'click',u));}function w(){var aa=o(s);if(aa&&t){aa.appendChild(t);t=null;}}function x(){if(q){q.cleanup();q=null;}if(p){p.release();p=null;}t=null;}function y(aa,ba){t=ba;u();}var z={init:function(aa,ba,ca){r=o(aa);s=aa;q=new g(r,ba,ca).subscribeDefaultEventsForRefresh();p=new m();p.addSubscriptions(h.subscribe(k.FILTER_SWITCH_BEGIN,x),h.subscribe(k.NEW_STORY_BAR_CLICK,function(){q.forceLoadIfEnoughTimePassed(ba.new_story_bar_delay_ms);}),h.subscribe('AdsRefreshHandler/AdsLoaded',v),h.subscribe('AdsRefreshHandler/AdsLoaded',w),h.subscribe('ProfileQuestionAnswered',y));v();l.onLeave(x);}};e.exports=z;});
__d("TypeaheadSubmitOnSelect",["Form","copyProperties"],function(a,b,c,d,e,f){var g=b('Form'),h=b('copyProperties');function i(j){"use strict";this._typeahead=j;}i.prototype.enable=function(){"use strict";this._subscription=this._typeahead.subscribe('select',function(){var j=this._typeahead.getCore().getElement().form;if(j)j.getAttribute('rel')=='async'?g.bootstrap(j):j.submit();}.bind(this));};i.prototype.disable=function(){"use strict";this._typeahead.unsubscribe(this._subscription);this._subscription=null;};h(i.prototype,{_subscription:null});e.exports=i;});
__d("legacy:SubmitOnSelectTypeaheadBehavior",["TypeaheadSubmitOnSelect"],function(a,b,c,d){var e=b('TypeaheadSubmitOnSelect');if(!a.TypeaheadBehaviors)a.TypeaheadBehaviors={};a.TypeaheadBehaviors.submitOnSelect=function(f){f.enableBehavior(e);};},3);